// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIT3mYYorY8oIB-CHnFe69UEXa9l1oYvQ',
    appId: '1:343311038577:web:c158fda77bddd5803e83d0',
    messagingSenderId: '343311038577',
    projectId: 'todoapp-dad27',
    authDomain: 'todoapp-dad27.firebaseapp.com',
    storageBucket: 'todoapp-dad27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWY8gvZcGMG1UPTyTgGJQ2ii340bIiNNc',
    appId: '1:343311038577:android:f04b1fbdf7948df63e83d0',
    messagingSenderId: '343311038577',
    projectId: 'todoapp-dad27',
    storageBucket: 'todoapp-dad27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy-mss8atiIsVuFktPqkjpgU-BRlNTXMg',
    appId: '1:343311038577:ios:75dc03b70a7dbb0d3e83d0',
    messagingSenderId: '343311038577',
    projectId: 'todoapp-dad27',
    storageBucket: 'todoapp-dad27.appspot.com',
    iosClientId: '343311038577-af9gulpapv3svah4f4io59dmnbvs1d34.apps.googleusercontent.com',
    iosBundleId: 'com.example.TodoPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy-mss8atiIsVuFktPqkjpgU-BRlNTXMg',
    appId: '1:343311038577:ios:35b92ae38f3fb3743e83d0',
    messagingSenderId: '343311038577',
    projectId: 'todoapp-dad27',
    storageBucket: 'todoapp-dad27.appspot.com',
    iosClientId: '343311038577-0n1gh9mrjfik86l2ahkn0o08vb570be2.apps.googleusercontent.com',
    iosBundleId: 'com.example.TodoPage.RunnerTests',
  );
}
